// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductOrders.API.Data;

#nullable disable

namespace ProductOrders.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductOrders.API.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3bd7748-4b1f-447e-aa68-d1bc4bff2460"),
                            Amount = 100m,
                            CreatedAt = new DateTime(2024, 5, 30, 19, 52, 19, 300, DateTimeKind.Utc).AddTicks(919),
                            CustomerEmail = "",
                            CustomerName = "John Doe",
                            ShippingAddress = "123 Main St, New York, NY 10030",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("67749942-13d7-4826-97bc-21fbb7d394c7"),
                            Amount = 200m,
                            CreatedAt = new DateTime(2024, 5, 30, 19, 52, 19, 300, DateTimeKind.Utc).AddTicks(931),
                            CustomerEmail = "",
                            CustomerName = "Jane Doe",
                            ShippingAddress = "456 Main St, New York, NY 10030",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
